### ISSUE TITLE
Some kind of typo

### ISSUE THREAD

**Issue by p-state** [Cr4sh/Aptiocalypsis#1]
https://github.com/Cr4sh/Aptiocalypsis/blob/master/aptiocalypsis.py#L89
I guess this is bug, cause (0 << 4) is nonsense. I believe it's (EBDA_ADDR << 4).

**Comment by Cr4sh** [comment]
Looks like result of some quick fixing: I don't remember why exactly I leaved this piece of code after the fix (it's really has no sense) and for this exact reason I don't want to touch it, maybe I will remember someday :)
