### ISSUE TITLE
Can Aptiocalypsis bypass APTIO V's Secure Flash (enable)?

### ISSUE THREAD

**Issue by commcad** [Cr4sh/Aptiocalypsis#2]
I am trying hard to release the Secure Flash checks that this BIOS has. So I can load and run a modded bios. Will this tool allow me to do so? Below is the bios in question

https://github.com/LattePandaTeam/LattePanda-Win10-Software/tree/master/Bios/LattePanda%20V1.2%20for%20CR200%20Z8350%20only/default%20BIOS/4G%20version

Tried everything, AFU, SPI/hardware level flashing, UEFITool, can't find any way to get this done. Any advice or help would be appreciated

Thanks

**Comment by commcad** [comment]
That is what I am trying to bypass ;)

![aptio-v_rsa_enabled](https://user-images.githubusercontent.com/19387951/30805838-de93ed9e-a225-11e7-87cd-db5d670f4671.jpg)

**Comment by Cr4sh** [comment]
In general, the answer is yes: you can use Aptiocalypsis to run your own SMM code that removes PRx flash write protection (see my other article on its bypass) and flashes modified firmware image into the flash.
